### ISSUE TITLE
Solution build and data access issues

### ISSUE THREAD

**Issue by papyr** [IntuitDeveloper/SampleApp-Webhooks-DotNet#1]
Hi I'm trying this, but it doe sbuild with RC core 1.

The C# .net support is lacking seriously, please update with more details on accessing data

Also, when I switch back to old MVC, the web hooks hang do not come back, is this updated to match the changes in the user access?

**Comment by nimisha84** [comment]
We do not have a plan to support .net core very soon unfortunately. However webhooks events should still deliver on any framework's app unless there is some other issue with the webhooks url or  you are not connected to the realm. 
Sorry for the late reply.
